-- CREATE SCHEMA EMPLOYEES_DB  AUTHORIZATION sa;

    DROP TABLE IF EXISTS TAS_BETC;
    -- Drop the Employee Sequence if it exists
    DROP SEQUENCE IF EXISTS TAS_BETC_SEQ;

    CREATE TABLE TAS_BETC (
        ID_NUMBER BIGINT NOT NULL,
        VERSION_ID BIGINT DEFAULT 0 NOT NULL,
        CMPNT_TAS_SP VARCHAR(25),
        CMPNT_TAS_ATA VARCHAR(25),
        CMPNT_TAS_AID VARCHAR(25),
        CMPNT_TAS_BPOA VARCHAR(25),
        CMPNT_TAS_EPOA VARCHAR(25),
        CMPNT_TAS_A VARCHAR(25),
        CMPNT_TAS_MAIN VARCHAR(25),
        CMPNT_TAS_SUB VARCHAR(25),
        ADMIN_BUR VARCHAR(250),
        GWA_TAS VARCHAR(35),
        GWA_TAS_NAME VARCHAR(250),
        AGENCY_NAME VARCHAR(250),
        BETC VARCHAR(35),
        BETC_NAME VARCHAR(250),
        EFF_DATE VARCHAR(35),
        SUSPEND_DATE VARCHAR(35),
        CREDIT VARCHAR(1),
        ADJ_BETC VARCHAR(35),
        STAR_TAS VARCHAR(35),
        STAR_DEPT_REG VARCHAR(35),
        STAR_DEPT_XFR VARCHAR(35),
        STAR_MAIN_ACCT VARCHAR(35),
        TXN_TYPE VARCHAR(35),
        ACCT_TYPE VARCHAR(35),
        ACCT_TYPE_DESCRIPTION VARCHAR(250),
        FUND_TYPE VARCHAR(35),
        FUND_TYPE_DESCRIPTION VARCHAR(250),
        PROCESS_DATETIME TIMESTAMP,
        FK_JOB_EXECUTION_ID BIGINT,
        PRIMARY KEY (ID_NUMBER)
    );

    -- Create the TASBETC sequence
    CREATE SEQUENCE TAS_BETC_SEQ AS BIGINT START 20 INCREMENT 10 MINVALUE 20 OWNED BY TAS_BETC.ID_NUMBER;

    GRANT INSERT, SELECT, UPDATE, DELETE
    ON TABLE TAS_BETC
    TO "SPRINGBATCH_APP_USER";

    GRANT USAGE
    ON SEQUENCE TAS_BETC_SEQ
    TO "SPRINGBATCH_APP_USER";