file:
  upload:
    job:
      beginningLinesToSkip: 2
      chunkSize: 25
      csvFileHeaders: componentTasSP,componentTasATA,componentTasAID,componentTasBPOA,componentTasEPOA,componentTasA,componentTasMain,componentTasSub,adminBureau,gwaTas,gwaTasName,agencyName,betc,betcName,effectiveDate,suspendDate,credit,adjustmentBetc,starTas,starDeptReg,starDeptXfr,starMainAccount,transactionType,accountType,accountTypeDescription,fundType,fundTypeDescription,blankComma
      cronSchedule: "*/60 * * * * *"
      fileUploadRootDirectory: /temp/upload-folder
      intervalInSeconds: 60
      skipLimit: 2
      postgreSQLDatabaseIPAddress: 192.168.2.185
management:
  endpoint:
    flyway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 8081
  servlet:
    context-path: /springbatchdemo
spring:
  batch:
    initialize-schema: never
    job:
      enabled: false
  datasource:
    driver-class-name: org.h2.Driver
    platform: "h2"
    url: jdbc:h2:mem:SPRING_BATCH_DEMO;DB_CLOSE_DELAY=-1
    username: sa
  flyway:
    baselineOnMigrate: true
    baselineDescription: "FLYWAY-BASELINE"
    enabled: true
    ignoreMissingMigrations: true
    locations: "classpath:db/migration/flyway/h2/common,classpath:db/migration/flyway/h2/bootable-data"
    outOfOrder: false
    validateOnMigrate: true
  h2:
    console:
      enabled: true
      path: /myh2
  servlet:
    multipart:
      max-file-size: 250MB
      max-request-size: 250MB
  jmx:
    default-domain: /springbatchdemo
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    open-in-view: true
    properties:
      hibernate:
        default_schema: PUBLIC
  main:
    allow-bean-definition-overriding: true

---

spring:
  profiles: postgresql-profile
  _comment: "This will be a Docker PostgreSQL Database"
  batch:
    table-prefix: spring_batch_demo.BATCH_
  datasource:
    driver-class-name: "org.postgresql.Driver"
    url: "jdbc:postgresql://${file.upload.job.postgreSQLDatabaseIPAddress}:8085/spring_batch_demo_db"
    username: "SPRINGBATCH_APP_USER"
    password: "mynonsecretpassw0rd"
    platform: "postgresql"
    _comment: "I hate Spring Boot you can't setup your own Datasource Config because it creates this Hikari datasource"
  flyway:
    create-schemas: false
    default-schema: spring_batch_demo
    locations: "classpath:db/migration/flyway/postgresql/common,classpath:db/migration/flyway/postgresql/bootable-data"
    mixed: true
    password: "mysecret"
    schemas: spring_batch_demo
    url: "jdbc:postgresql://${file.upload.job.postgreSQLDatabaseIPAddress}:8085/spring_batch_demo_db"
    user: "DB_OWNER_USER"
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    properties:
      hibernate:
        default_schema: spring_batch_demo
        dialect: "org.hibernate.dialect.PostgreSQL95Dialect"
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
        temp:
          use_jdbc_metadata_defaults: false
    open-in-view: true
    show-sql: true

---
spring:
  profiles: localinstall-postgresql-profile
  _comment: "This will be a local installed PostgreSQL Database"
  batch:
    table-prefix: spring_batch_demo.BATCH_
  datasource:
    driver-class-name: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:5432/spring_batch_demo_db"
    username: "SPRINGBATCH_APP_USER"
    password: "mynonsecretpassw0rd"
    platform: "postgresql"
    _comment: "I hate Spring Boot you can't setup your own Datasource Config because it creates this Hikari datasource"
  flyway:
    create-schemas: false
    default-schema: spring_batch_demo
    locations: "classpath:db/migration/flyway/postgresql/common,classpath:db/migration/flyway/postgresql/bootable-data"
    mixed: true
    password: "mysecret"
    schemas: spring_batch_demo
    url: "jdbc:postgresql://localhost:5432/spring_batch_demo_db"
    user: "DB_OWNER_USER"
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    properties:
      hibernate:
        default_schema: spring_batch_demo
        dialect: "org.hibernate.dialect.PostgreSQL95Dialect"
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
        temp:
          use_jdbc_metadata_defaults: false
    open-in-view: true
    show-sql: true