-- CREATE SCHEMA EMPLOYEES_DB  AUTHORIZATION sa;

    DROP TABLE TAS_BETC IF EXISTS;

    CREATE SEQUENCE TAS_BETC_SEQ START WITH 20 INCREMENT BY 10;

    CREATE TABLE TAS_BETC (
        ID_NUMBER BIGINT DEFAULT TAS_BETC_SEQ.nextval,
        VERSION_ID BIGINT DEFAULT 0 NOT NULL,
        CMPNT_TAS_SP VARCHAR(25),
        CMPNT_TAS_ATA VARCHAR(25),
        CMPNT_TAS_AID VARCHAR(25),
        CMPNT_TAS_BPOA VARCHAR(25),
        CMPNT_TAS_EPOA VARCHAR(25),
        CMPNT_TAS_A VARCHAR(25),
        CMPNT_TAS_MAIN VARCHAR(25),
        CMPNT_TAS_SUB VARCHAR(25),
        ADMIN_BUR VARCHAR(250),
        GWA_TAS VARCHAR(35),
        GWA_TAS_NAME VARCHAR(250),
        AGENCY_NAME VARCHAR(250),
        BETC VARCHAR(35),
        BETC_NAME VARCHAR(250),
        EFF_DATE VARCHAR(35),
        SUSPEND_DATE VARCHAR(35),
        CREDIT TINYINT(1),
        ADJ_BETC VARCHAR(35),
        STAR_TAS VARCHAR(35),
        STAR_DEPT_REG VARCHAR(35),
        STAR_DEPT_XFR VARCHAR(35),
        STAR_MAIN_ACCT VARCHAR(35),
        TXN_TYPE VARCHAR(35),
        ACCT_TYPE VARCHAR(35),
        ACCT_TYPE_DESCRIPTION VARCHAR(250),
        FUND_TYPE VARCHAR(35),
        FUND_TYPE_DESCRIPTION VARCHAR(250),
        PROCESS_DATETIME DATE,
        FK_JOB_EXECUTION_ID BIGINT,
        PRIMARY KEY (ID_NUMBER)
    );
