
DROP TABLE SHEDLOCK IF EXISTS;

-- Create ShedLock Tables
CREATE TABLE SHEDLOCK(NAME VARCHAR(64) NOT NULL, LOCK_UNTIL TIMESTAMP NOT NULL,
    LOCKED_AT TIMESTAMP NOT NULL, LOCKED_BY VARCHAR(255) NOT NULL, PRIMARY KEY (NAME));