-- CREATE SCHEMA EMPLOYEES_DB  AUTHORIZATION sa;

    DROP TABLE TAS_BETC IF EXISTS;

    CREATE SEQUENCE TAS_BETC_SEQ START WITH 20 INCREMENT BY 10;
    CREATE SEQUENCE FILE_UPLOAD_JOB_HEADER_SEQ START WITH 20 INCREMENT BY 10;
    CREATE SEQUENCE PROCESSING_ERROR_SEQ START WITH 20 INCREMENT BY 10;

    CREATE TABLE TAS_BETC (
        ID_NUMBER BIGINT DEFAULT TAS_BETC_SEQ.nextval,
        VERSION_ID BIGINT DEFAULT 0 NOT NULL,
        CMPNT_TAS_SP VARCHAR(25),
        CMPNT_TAS_ATA VARCHAR(25),
        CMPNT_TAS_AID VARCHAR(25),
        CMPNT_TAS_BPOA VARCHAR(25),
        CMPNT_TAS_EPOA VARCHAR(25),
        CMPNT_TAS_A VARCHAR(25),
        CMPNT_TAS_MAIN VARCHAR(25),
        CMPNT_TAS_SUB VARCHAR(25),
        ADMIN_BUR VARCHAR(250),
        GWA_TAS VARCHAR(35),
        GWA_TAS_NAME VARCHAR(250),
        AGENCY_NAME VARCHAR(250),
        BETC VARCHAR(35),
        BETC_NAME VARCHAR(250),
        EFF_DATE VARCHAR(35),
        SUSPEND_DATE VARCHAR(35),
        CREDIT TINYINT(1),
        ADJ_BETC VARCHAR(35),
        STAR_TAS VARCHAR(35),
        STAR_DEPT_REG VARCHAR(35),
        STAR_DEPT_XFR VARCHAR(35),
        STAR_MAIN_ACCT VARCHAR(35),
        TXN_TYPE VARCHAR(35),
        ACCT_TYPE VARCHAR(35),
        ACCT_TYPE_DESCRIPTION VARCHAR(250),
        FUND_TYPE VARCHAR(35),
        FUND_TYPE_DESCRIPTION VARCHAR(250),
        PROCESS_DATETIME TIMESTAMP,
        FK_FILE_UPLOAD_JOB_HEADER_ID BIGINT NOT NULL,
        PRIMARY KEY (ID_NUMBER)
    );

    CREATE TABLE FILE_UPLOAD_JOB_HEADER (
        FILE_UPLOAD_JOB_HEADER_ID BIGINT DEFAULT FILE_UPLOAD_JOB_HEADER_SEQ.nextval,
        VERSION_ID BIGINT DEFAULT 0 NOT NULL,
        FK_JOB_EXECUTION_ID BIGINT,
        READ_COUNT BIGINT,
        EXIT_CODE VARCHAR(2500),
        STATUS VARCHAR(10),
        FILE_NAME VARCHAR(250),
        FILE_UPLOAD_DATETIME TIMESTAMP,
        PRIMARY KEY (FILE_UPLOAD_JOB_HEADER_ID)
    );

    CREATE TABLE PROCESSING_ERROR (
        PROCESSING_ERROR_ID BIGINT DEFAULT PROCESSING_ERROR_SEQ.nextval,
        VERSION_ID BIGINT DEFAULT 0 NOT NULL,
        FK_FILE_UPLOAD_JOB_HEADER_ID BIGINT NOT NULL,
        ERROR_DESCRIPTION VARCHAR(2500),
        STEP_TYPE_ERROR VARCHAR(30),
        PRIMARY KEY (PROCESSING_ERROR_ID)
    );

    ALTER TABLE TAS_BETC
        ADD CONSTRAINT FK_JOB_HEADER_TAS_BETC_CONSTRAINT
        FOREIGN KEY (FK_FILE_UPLOAD_JOB_HEADER_ID)
        REFERENCES FILE_UPLOAD_JOB_HEADER;

    ALTER TABLE PROCESSING_ERROR
        ADD CONSTRAINT FK_JOB_HEADER_PROCESSING_ERROR_CONSTRAINT
        FOREIGN KEY (FK_FILE_UPLOAD_JOB_HEADER_ID)
        REFERENCES FILE_UPLOAD_JOB_HEADER;
