version: '3'
services:
  spring-batch-demo-server1:
    container_name: springbatch-demo-server1-container
    environment:
      - JAVA_OPTS=
        -Dfile.upload.job.fileUploadRootDirectory=/app
        -Dspring.profiles.active=postgresql-profile
        -Dspring.datasource.url=jdbc:postgresql://192.168.2.185:8085/spring_batch_demo_db
        -Dspring.flyway.url=jdbc:postgresql://192.168.2.185:8085/spring_batch_demo_db
        -Dserver.port=8081
    image: com.tim.example-spring-batch-excel:0.0.1-SNAPSHOT
    ports:
      - "8081:8081"
    restart: always
    volumes:
      - /temp/upload-folder:/app
  spring-batch-demo-server2:
    container_name: springbatch-demo-server2-container
    environment:
      - JAVA_OPTS=
        -Dfile.upload.job.fileUploadRootDirectory=/app
        -Dspring.profiles.active=postgresql-profile
        -Dspring.datasource.url=jdbc:postgresql://192.168.2.185:8085/spring_batch_demo_db
        -Dspring.flyway.url=jdbc:postgresql://192.168.2.185:8085/spring_batch_demo_db
        -Dserver.port=8082
    image: com.tim.example-spring-batch-excel:0.0.1-SNAPSHOT
    ports:
      - "8082:8082"
    restart: always
    volumes:
      - /temp/upload-folder:/app
# Compose using the environment file
# docker-compose --env-file .env.server2 up
