-- Revoking the ability to do anything in the Public schema
REVOKE CREATE ON SCHEMA public FROM PUBLIC;

-- Creating the base schema for the service
CREATE SCHEMA IF NOT EXISTS spring_batch_demo;

-- Role: "DB_OWNER_USER"
-- DROP ROLE "DB_OWNER_USER";

CREATE ROLE "DB_OWNER_USER" WITH
  LOGIN
  PASSWORD 'mysecret'
  SUPERUSER
  INHERIT
  CREATEDB
  CREATEROLE
  NOREPLICATION;

-- Role: "SPRINGBATCHAPPROLE"
-- DROP ROLE "SPRINGBATCHAPPROLE";

CREATE ROLE "SPRINGBATCHAPPROLE" WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION;

-- Role: "EMPLOYEE_APP_USER"
-- DROP ROLE "EMPLOYEE_APP_USER";

CREATE ROLE "SPRINGBATCH_APP_USER" WITH
  LOGIN
  PASSWORD 'mynonsecretpassw0rd'
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION;

GRANT "SPRINGBATCHAPPROLE" TO "SPRINGBATCH_APP_USER";

GRANT USAGE ON SCHEMA spring_batch_demo TO "SPRINGBATCHAPPROLE";

ALTER DEFAULT PRIVILEGES IN SCHEMA spring_batch_demo GRANT INSERT, SELECT, UPDATE, DELETE ON tables TO "SPRINGBATCHAPPROLE";
ALTER ROLE "SPRINGBATCH_APP_USER" IN DATABASE spring_batch_demo_db SET search_path TO spring_batch_demo;