-- Revoking the ability to do anything in the Public schema
REVOKE CREATE ON SCHEMA public FROM PUBLIC;

-- Creating the base schema for the service
CREATE SCHEMA IF NOT EXISTS GINV_BATCH;

CREATE ROLE "DB_OWNER_USER" WITH
  LOGIN
  PASSWORD 'mysecret'
  SUPERUSER
  INHERIT
  CREATEDB
  CREATEROLE
  NOREPLICATION;

CREATE ROLE "SPRINGBATCHAPPROLE" WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION;

CREATE ROLE "SPRINGBATCH_APP_USER" WITH
  LOGIN
  PASSWORD 'mynonsecretpassw0rd'
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION;

GRANT "SPRINGBATCHAPPROLE" TO "SPRINGBATCH_APP_USER";

GRANT USAGE ON SCHEMA GINV_BATCH TO "SPRINGBATCHAPPROLE";

ALTER DEFAULT PRIVILEGES IN SCHEMA GINV_BATCH GRANT INSERT, SELECT, UPDATE, DELETE ON tables TO "SPRINGBATCHAPPROLE";
ALTER ROLE "SPRINGBATCH_APP_USER" IN DATABASE spring_batch_demo_db SET search_path TO GINV_BATCH;