-- Role: "DB_OWNER_USER"
-- DROP ROLE "DB_OWNER_USER";

CREATE ROLE "DB_OWNER_USER" WITH
  LOGIN
  PASSWORD 'mysecret'
  SUPERUSER
  INHERIT
  CREATEDB
  CREATEROLE
  NOREPLICATION;

-- Role: "SPRINGBATCHAPPROLE"
-- DROP ROLE "SPRINGBATCHAPPROLE";

CREATE ROLE "SPRINGBATCHAPPROLE" WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION;

-- Role: "EMPLOYEE_APP_USER"
-- DROP ROLE "EMPLOYEE_APP_USER";

CREATE ROLE "SPRINGBATCH_APP_USER" WITH
  LOGIN
  PASSWORD 'mynonsecretpassw0rd'
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION;

GRANT "SPRINGBATCHAPPROLE" TO "SPRINGBATCH_APP_USER";